name: ci-golang-worflow
on:
  pull_request:
    branches:
       - develop
jobs:
  check-application: #nome do job
    runs-on: ubuntu-latest #qual ambiente ele irá rodar -> aqui escolhemos o 
    strategy:
      matrix:
        go: ['1.14', '1.15', '1.17']
    steps: #definimos quais são os passos
      - uses: actions/checkout@v2 #aqui definimos as depedências que iremos usar
      - uses: actions/setup-go@v2
        with: # qual a versão que iremos rodar 
          go-version: ${{matrix.go}}
      - run: go test -v ./... # o que rodamos em nosso worflow
      - run: go run src/math.go