name: ci-golang-worflow
on:
  pull_request:
    branches:
       - develop
jobs:
  check-application: #nome do job
    runs-on: ubuntu-latest #qual ambiente ele irá rodar -> aqui escolhemos o github
    steps: #definimos quais são os passos
      - uses: actions/checkout@v2 #aqui definimos as depedências que iremos usar
      - uses: actions/setup-go@v2
        with: # qual a versão que iremos rodar 
          go-version: 1.17
      - run: go test -v ./... # o que rodamos em nosso worflow
      - run: go run src/math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
      

      ##login no dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ## buildando nossa imagem docker
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: georginho/test-docker:latest
          build-args:
            arg1=value1
            arg2=value2